### ISSUE TITLE
Great Stuff. However, cannot comprehend what column "Proportion_DE_2020" in Data/age_data.csv

### ISSUE THREAD

**Issue by abdylan** [o0oBluePhoenixo0o/COVID_19-Social-Dist-Simulation#1]

**Comment by o0oBluePhoenixo0o** [comment]
Thanks for the comment. 
Proportion_DE_2020 is the proportion of population within the age cohort in Germany in year 2019.
I used the pyramid age to get the age distribution and then group them into buckets, for example: proportion of population from age 0-9 in Germany is ~ 17% of the total population / for age 10-19 is ~ 16% of the total population and so on...

**Comment by abdylan** [comment]
Total Population = 83M
Proportion for Age bucket 0-9 years: 9.2% (approx 8M)

Moreover, Age Bucket 50-59 should represent the largest value for this?
tl;dr -->> Doesn't the column "Proportion" rather than "Proportion_DE_2020" represent this more?

**Comment by o0oBluePhoenixo0o** [comment]
Thanks a lot for pointing out! 
Seems like I assigned the wrong column names and used it for my projections.
I have changed the codes in my github as well as on medium article to match the correct rate. Turns out the social distance 90% looks even better now with the correct rate (only 4k deaths after 6 months)

Again thanks :) and stay safe!
